version: '3.8'

services:
  frontend:
    build: ./frontend/todo-react-app
    image: christechstarter/frontend:latest
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./backend
    image: christechstarter/backend:latest
    ports:
      - "3050:3050"
    environment:
      - DATABASE_URL=postgresql://POSTGRES_USER:POSTGRES_PASSWORD@db:5432/tu_do
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tech
      POSTGRES_DB: tu_do
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
