FROM nginx:1.25.0-alpine

COPY /dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]




# FROM node:18-bullseye

# WORKDIR /app

# COPY package.json ./

# RUN npm install

# COPY . .

# EXPOSE 5173

# CMD ["npm", "run", "devdocker"]
